### ISSUE TITLE
Push/pull measurement ids on Kafka

### ISSUE THREAD

**Issue by romain-fontugne** [InternetHealthReport/raclette#20]
The list of 'long lasting' measurement ids should be retrieved and updated on kafka

**Comment by ritikBhandari** [comment]
@romain-fontugne Can I work on this if it is still open and nobody is working on it?

**Comment by romain-fontugne** [comment]
ah sorry this one is already done. I forgot to close this issue. The code is in a different repo: https://github.com/InternetHealthReport/kafka-toolbox/blob/master/atlas/producers/getMsmIds.py

thanks anyways!

**Comment by ritikBhandari** [comment]
No worries :)
